const getters = {
  sidebar: state => state.app.sidebar,
  language: state => state.app.language,
  size: state => state.app.size,
  device: state => state.app.device,
  visitedViews: state => state.tagsView.visitedViews,
  cachedViews: state => state.tagsView.cachedViews,
  token: state => state.user.token,
  avatar: state => state.user.avatar,
  name: state => state.user.name,
  email: state => state.user.email,
  is_staff: state => state.user.is_staff,
  is_active: state => state.user.is_active,
  is_superuser: state => state.user.is_superuser,
  date_joined: state => state.user.date_joined,
  introduction: state => state.user.introduction,
  roles: state => state.user.roles,
  permission_routes: state => state.permission.routes,
  errorLogs: state => state.errorLog.logs,
  serverAddress: state => state.settings.serverAddress,
  serverBaseUrl: state => state.settings.serverBaseUrl,
}
export default getters
