# Generated by Django 4.2.7 on 2023-12-03 02:09

import api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='self ID', primary_key=True, serialize=False)),
                ('node_name', models.CharField(help_text='module name, unique but delete', max_length=128)),
                ('id', models.CharField(blank=True, default='', help_text='node id for AutoRunX, auto generate by program', max_length=128)),
                ('name', models.CharField(db_index=True, help_text='node name', max_length=128)),
                ('node_type', models.CharField(choices=[('evtx', 'event transmit'), ('evrx', 'event receive'), ('dtio', 'data input/output'), ('dtpc', 'data process'), ('ctrl', 'flow control'), ('func', 'flow function')], help_text='node type', max_length=4)),
                ('pre_edge_id', models.TextField(default='[]')),
                ('nxt_edge_id', models.TextField(default='[]')),
                ('input', models.TextField(default='{}')),
                ('input_type', models.TextField(default='{}')),
                ('input_intro', models.TextField(default='{}')),
                ('output', models.TextField(default='{}')),
                ('output_type', models.TextField(default='{}')),
                ('output_intro', models.TextField(default='{}')),
                ('readme', models.TextField(blank=True, default='', help_text='README.md', null=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('delete_time', models.DateTimeField(blank=True, default=None, help_text='logic delete', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='self ID', primary_key=True, serialize=False)),
                ('error', models.CharField(blank=True, help_text='error', max_length=128)),
                ('error_type', models.CharField(blank=True, help_text='error type', max_length=128)),
                ('error_data', models.TextField(blank=True, default='', help_text='error data', null=True)),
                ('mark', models.TextField(blank=True, default='', help_text='mark', null=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('delete_time', models.DateTimeField(blank=True, default=None, help_text='logic delete', null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='self ID', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='self name', max_length=128)),
                ('upload_run_config', models.BooleanField(default=False, help_text='whether to upload run configuration file')),
                ('run_config_file', models.FileField(blank=True, help_text='run configuration file', null=True, upload_to=api.models.app_user_path)),
                ('plan_start_time', models.DateTimeField(blank=True, help_text='time of planning to start', null=True)),
                ('start_running_time', models.DateTimeField(blank=True, help_text='start running time', null=True)),
                ('end_running_time', models.DateTimeField(blank=True, help_text='end running time', null=True)),
                ('abort_running_time', models.DateTimeField(blank=True, help_text='manual or abnormal abort running time', null=True)),
                ('run_time_error', models.TextField(blank=True, default='', help_text='information that an error occurred at runtime', null=True)),
                ('mark', models.TextField(blank=True, default='', help_text='mark', null=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('delete_time', models.DateTimeField(blank=True, default=None, help_text='logic delete', null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='self ID', primary_key=True, serialize=False)),
                ('action', models.CharField(blank=True, help_text='action', max_length=128)),
                ('action_type', models.CharField(blank=True, help_text='action type', max_length=128)),
                ('action_data', models.TextField(blank=True, default='', help_text='action data', null=True)),
                ('mark', models.TextField(blank=True, default='', help_text='mark', null=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('delete_time', models.DateTimeField(blank=True, default=None, help_text='logic delete', null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
