# Generated by Django 4.2.7 on 2023-12-11 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_node_lang'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='lib_id',
            field=models.CharField(choices=[('opensource', 'OpenSource')], default=None, help_text='node lang', max_length=128),
        ),
    ]
