# Generated by Django 4.2.7 on 2023-12-16 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_node_lib_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='nxt_edge_id_intro',
            field=models.TextField(default='[]'),
        ),
    ]
